# Generated by Django 5.0.13 on 2025-03-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedata',
            old_name='urls',
            new_name='url',
        ),
    ]
