# Generated by Django 5.0.13 on 2025-03-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_urls_imagedata_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=250)),
                ('due_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ImageData',
        ),
    ]
