# Generated by Django 5.0.13 on 2025-03-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userinfo_delete_imagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='due_date',
            field=models.CharField(max_length=250),
        ),
    ]
